// This file is generated by Firebase Extensions Studio.
'use server';

/**
 * @fileOverview Generates a chapter outline for a given topic.
 *
 * - generateChapterOutline - A function that generates a chapter outline.
 * - GenerateChapterOutlineInput - The input type for the generateChapterOutline function.
 * - GenerateChapterOutlineOutput - The return type for the generateChapterOutline function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateChapterOutlineInputSchema = z.object({
  topic: z.string().describe('The topic for which to generate a chapter outline.'),
});
export type GenerateChapterOutlineInput = z.infer<typeof GenerateChapterOutlineInputSchema>;

const GenerateChapterOutlineOutputSchema = z.object({
  outline: z.string().describe('The generated chapter outline.'),
});
export type GenerateChapterOutlineOutput = z.infer<typeof GenerateChapterOutlineOutputSchema>;

export async function generateChapterOutline(input: GenerateChapterOutlineInput): Promise<GenerateChapterOutlineOutput> {
  return generateChapterOutlineFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateChapterOutlinePrompt',
  input: {schema: GenerateChapterOutlineInputSchema},
  output: {schema: GenerateChapterOutlineOutputSchema},
  prompt: `You are an expert in structuring content for academic papers.

  Based on the topic provided, generate a detailed chapter outline.

  Topic: {{{topic}}}
  `,
});

const generateChapterOutlineFlow = ai.defineFlow(
  {
    name: 'generateChapterOutlineFlow',
    inputSchema: GenerateChapterOutlineInputSchema,
    outputSchema: GenerateChapterOutlineOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
