// This file is generated by Firebase Extensions Studio.
'use server';

/**
 * @fileOverview Génère un plan de chapitre pour un sujet donné.
 *
 * - generateChapterOutline - Une fonction qui génère un plan de chapitre.
 * - GenerateChapterOutlineInput - Le type d'entrée pour la fonction generateChapterOutline.
 * - GenerateChapterOutlineOutput - Le type de retour pour la fonction generateChapterOutline.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateChapterOutlineInputSchema = z.object({
  topic: z.string().describe('Le sujet pour lequel générer un plan de chapitre.'),
});
export type GenerateChapterOutlineInput = z.infer<typeof GenerateChapterOutlineInputSchema>;

const GenerateChapterOutlineOutputSchema = z.object({
  outline: z.string().describe('Le plan de chapitre généré.'),
});
export type GenerateChapterOutlineOutput = z.infer<typeof GenerateChapterOutlineOutputSchema>;

export async function generateChapterOutline(input: GenerateChapterOutlineInput): Promise<GenerateChapterOutlineOutput> {
  return generateChapterOutlineFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateChapterOutlinePrompt',
  input: {schema: GenerateChapterOutlineInputSchema},
  output: {schema: GenerateChapterOutlineOutputSchema},
  prompt: `Vous êtes un expert en structuration de contenu pour les articles académiques.

  En fonction du sujet fourni, générez un plan de chapitre détaillé.

  Sujet : {{{topic}}}
  `,
});

const generateChapterOutlineFlow = ai.defineFlow(
  {
    name: 'generateChapterOutlineFlow',
    inputSchema: GenerateChapterOutlineInputSchema,
    outputSchema: GenerateChapterOutlineOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
